### PR TITLE
Development to master

### PR DESCRIPTION
**Pull request by tnowotny**
@kernfel, I think it is time to merge your developments into the master branch. I am also considering to list StdpC on nitrc.org, so would be good to have a good working version as current master.

### CODE REVIEW

**Comment by kernfel** [comment]
Thomas, I'm working on a final piece (putting the data saving routine into a separate thread), but I'm pretty much through with the manual. Could you have a look through that, particularly the first (authorship) and last (acknowledgements) bits? Thank you!
https://github.com/tnowotny/stdpc/blob/a5c6bccd6bf6d22b2d5709c215b093c7f26a5028/manual/manual.pdf

**Comment by tnowotny** [comment]
@kernfel, I am reading the manual. What would you prefer me to do: Attach some comments on the pdf or edit the sources?

**Comment by kernfel** [comment]
Do whatever works best for you!

**Comment by tnowotny** [comment]
Should I just merge this now?

**Comment by kernfel** [comment]
Yeah, let's. I'll make a release with executables next week.

**Pull request merged**
