### PR TITLE
Build compatibility update

### PR DESCRIPTION
**Pull request by kernfel**
@tnowotny, let me know if there any other things that your Qt version doesn't know yet.

### CODE REVIEW

**Comment by tnowotny** [comment]
Ok ... I tried compiling again and now it picks on this:
"invalid use of non-static member function 'void QCheckBox::stateChanged(int)'
in GraphDlg.cpp: 272
Are you just missing the SIGNAL() macro here?

**Comment by tnowotny** [comment]
By the way I am working with QT 5.3.2 because it was already installed on the box. I could update I suppose ...?

**Comment by kernfel** [comment]
Hah, good one. There's no reason that should've ever compiled, but I remember I've had a similar issue before.
I'd rather bash through a few of these issues.. after all, I've advertised build compatibility as Qt 5, not 5.7.

**Comment by tnowotny** [comment]
It builds now. I picked up a few warnings about unused parameters. Are you  bothered about those?
unused 't' in GapJunction.cpp 15
unsued 'dt' in GapJunction.cpp 15
unused 't' in AbHH.cpp 51

**Comment by kernfel** [comment]
I'd left them in for implicit documentation, but I guess that could be done better (like in the declaration, or by comment).

**Comment by tnowotny** [comment]
now I was playing with the simuldaq. It seems to load the example file StdpCIn1.dat fine but when I run it with the new shiny graphing on, it shows only zeros ...
Probably a detail about simuldaq ... ?
PS: I also made a gap junction between the two input channels, and the resulting output is indeed all zero as well, suggesting it's not the plotting but the import of the voltages from file.

**Comment by kernfel** [comment]
Ah, I see what's happening there. Input/Output channel setup defaults all fields to 0, including the conversion factor.

**Comment by tnowotny** [comment]
yes ... I see it ... could have seen that myself ... guess I am rusty.

**Comment by kernfel** [comment]
To be fair, those 0 defaults are only there for SimulDAQs, and really shouldn't.

**Comment by tnowotny** [comment]
played a bit more ... but the voltage isn't displaying. I wonder whether we should not worry about it and discontinue the simulDAQ?

**Comment by kernfel** [comment]
It's working over here, displays fine - although of course the input file is in mV, so the conversion factor needs to be 0.001 to display in (normal) graph range.

**Comment by tnowotny** [comment]
ah ... and the time scale is to be adjusted as well. It runs now but occasionally it hangs (I suspect when the file loops over but not sure ...)
`good enough' for SimulDAQ I would say.

**Comment by tnowotny** [comment]
The other thing I notice that it has build without NIDAQ ... what do you need to do to have NIDAQ support compiled in?

**Comment by kernfel** [comment]
Nothing other than an installation of NIDAQmx (15.5.1+), I believe.

**Comment by tnowotny** [comment]
Hum ... I have 16.0.1 installed but qmake doesn't seem to pick that up. How is it supposed to detect whether NIDAQMX is installed or not? And where it resides?

**Comment by kernfel** [comment]
Ah - add a `CONFIG+=nidaqmx` into the qmake call. I don't know how I'd detect the presence or otherwise of system libraries...

**Comment by tnowotny** [comment]
ok ... that works ... as someone building from inside QTCreator I have to add it to the .pro file.
Would it be worth having a commented line in there that offers that? with a comment: "uncomment here if you want nidaqmx included"?

**Comment by kernfel** [comment]
You can actually add build-time parameters in the Projects tab, but yes, I'll add something in near the top. I've also found a way to detect NIDAQmx presence in the environment, so I'll auto-detect when possible.

**Comment by tnowotny** [comment]
ok ... that all works well over here.
One more detail: I got the runtime error message "QTextCursor::setPosition: Position '20' out of range
But with no other consequences - have you seen it before? - does it matter?

**Comment by kernfel** [comment]
Huh, no, that's new. I also can't see a single use of either QTextCursor or its setPosition anywhere. Do you know what prompted it?

**Comment by tnowotny** [comment]
When I activate the Nat'l Instruments data source by clicking the checkbox on the main screen and it turns red (because it can't find Dev1 (I don't have any hardware)), then this error message appears in the QtCreator Application Output window ... I have no idea what this means ;-)
PS: If I do the same with a DigiData 1200(A) device, the error message says the same except "Position 19" instead of "Position 20" ... very mysterious.
A badly configured simulDaq gives the error with "Position 11"

**Comment by kernfel** [comment]
Huh. Do you get the "Bad news: Dev1 not found or opened successfully!" message in the log?

**Comment by tnowotny** [comment]
yes ... everything works as expected there

**Comment by kernfel** [comment]
Can't replicate. Might be a bug in Qt 5.3, possibly related to https://bugreports.qt.io/browse/QTBUG-38178 ... although that's assuming that a QLabel has a cursor, which would be rather daft. Anyway, if it doesn't break anything, I think I can live with it. :)

**Comment by tnowotny** [comment]
I'd be happy to merge the pull request then - ok?

**Comment by kernfel** [comment]
Yup.

**Pull request merged**
