### PR TITLE
Adding a logo

### LINKED ISSUE #22: Logo
A logo would be nice, I guess! I'm thinking along the lines of connecting a computer chip and a neuron in a loop. Not particularly original, but gets the message across?

### PR DESCRIPTION
**Pull request by kernfel**
Closes #22

Comments welcome. :)

image

### CODE REVIEW

**Comment by kernfel** [comment]
The transparency doesn't play too well with dark backgrounds (like here, in dark mode). Also, I'm not sure how well this'll scale down to, say, the app icon in Windows.

**Comment by tnowotny** [comment]
It looks fun. My only point would be that the "StdpC" text could be a bit bigger; would it be breaking the aesthetics if  it was in the "GeNN dark red"?

**Comment by tnowotny** [comment]
(I mean the text "StdpC" in red)

**Comment by kernfel** [comment]
Sure thing. Do you have an RGB code for that?

**Comment by tnowotny** [comment]
let me look it up

**Comment by kernfel** [comment]
Got it from the docs CSS, #bb0000.

**Comment by tnowotny** [comment]
It is not totally uniform but around (167,0,0)

**Comment by tnowotny** [comment]
Ok ... that's pretty similar. I guess we have a couple of different versions flying round

**Comment by kernfel** [comment]
image

**Comment by kernfel** [comment]
That incidentally solves the black background issue, for what it's worth.

**Comment by tnowotny** [comment]
I am fine with it .. are you happy?

**Comment by kernfel** [comment]
Largely. I feel the font could be rounder, but I'm not sure I'm ready to commit to Comic Sans for it :grin:

**Comment by tnowotny** [comment]
I can't even remember what the GeNN font is

**Comment by kernfel** [comment]
Architects Daughter, apparently. Looks pretty good, I think!
image

**Comment by kernfel** [comment]
I'll sleep over it, see if I still like it tomorrow.

**Comment by tnowotny** [comment]
sounds like a good plan ... is there a bold version of the font?

**Comment by kernfel** [comment]
Sadly, there isn't. I'll see if there's a way to increase the weight in
inkscape, though.

**Comment by kernfel** [comment]
Adding a stroke colour to the text and changing its thickness does the trick.
image

**Comment by kernfel** [comment]
image
Now I'm happy, I think. Let me know if you have any lingering concerns!

**Comment by tnowotny** [comment]
Am I understanding from your last push that it's now square?

**Comment by tnowotny** [comment]
wow ... ok ... I measured it and it's square. For some reason it looks much taller than wide to my naked eye - really strange effect.
To be honest - I liked it better before it was squarified but no strong opinion ;-) 
The font is now nice.

**Comment by kernfel** [comment]
I don't disagree, the neuron looked a little squished. So... back to the previous meshes, but with a little vertical space to make it square anyway.
image

**Comment by tnowotny** [comment]
ok ... perfect. let's call it done.

**Pull request merged**
